name: Weekly Firebase Sync
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install firebase-admin
      - name: Run Task
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: node --experimental-network-imports ./jobs/weekly-task.js
