name: Weekly Email

on:
  schedule:
    # Runs at 00:00 UTC every monday
    - cron: '*/5 * * * *'
  # Allows you to manually trigger the script from the Actions tab
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi
        
      - name: Execute JavaScript file
        run: node --experimental-network-imports jobs/weekly-run.js
